### ISSUE TITLE
Loading bank page stuck

### ISSUE THREAD

**Issue by Balasnest** [razorpay/react-native-razorpay#113] opened 2018-09-25 11:47 UTC
Issue is happening in **android** only. Unable to pay from "**debit/credit card**" and **UPI** at **Pay** until click **Retry** button. Tried with **testing and Production** bank page. Working for **Netbanking** at first **Pay** click

**Steps to reproduce:**
1.  click **Pay**
2. Loading bank page (stuck). Not able to see demo and production bank page
3. **Cancel Payment** and click **Retry**.
4. Now click **Pay** again, got demo bank page with **success** / **failure** button.

> **NOTE**: I was able to do first Pay in 1.5.0 Version and its working in card, banking and UPI.

"**react-native-razorpay**": "2.0.1" (same thing happening in **2.0.0**, **2.0.2**, **2.0.3**, **2.0.5**, **2.0.9**)

**Environment**:
  OS: macOS High Sierra 10.13
  Node: 8.9.4
  Yarn: 1.3.2
  npm: 4.6.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.51.0 => 0.51.0

![download](https://user-images.githubusercontent.com/6050520/46408327-66fc4800-c72f-11e8-89ce-6169df112b36.png)

**Comment by meghaptg** [comment] 2018-10-03 11:37
+1 
facing the same issue on android
used library version: 2.0.9

**Comment by iThink32** [comment] 2018-10-03 13:12
@Balasnest , getting it checked will give an update tom

**Comment by umanghome** [comment] 2018-10-03 13:30
@Bala2103, would you be able to provide an APK in debug-mode?

**Comment by umanghome** [comment] 2018-10-03 13:30
Also, what device is this?

**Comment by umanghome** [comment] 2018-10-03 13:34
@Balasnest - Would you be able to provide an APK in debug mode? Also, what device is this?

**Comment by Balasnest** [comment] 2018-10-03 13:35
Tried with 4 devices.
Android 4.4 - Samsung
Android 6.1 - Redmi, one plus one
Android 7.1 - Nexus 5

**Comment by georgian3688** [comment] 2018-10-04 06:01
I got too know its bug in razorpay. I am also facing the exact issue, payment is not happening at the first time for credit/ Debit card. Can somebody fix this issue or let me know if there is any alternative to do so.

**Comment by Balasnest** [comment] 2018-10-04 17:21
@umanghome sent to your mail.

**Comment by georgian3688** [comment] 2018-10-08 08:15
@Balasnest @meghaptg  Did you manage to get it work?
@umanghome @iThink32 Any solution for this ? I am still facing the same issue in android only. I have checked in ios (it is working fine).

**Comment by iThink32** [comment] 2018-10-08 08:49
@georgian3688 we are working on the fix for android , we will update it here when we fix this.

**Comment by georgian3688** [comment] 2018-10-08 09:13
@iThink32  Thanks for your quick reply.  Please update once its resolve.

**Comment by Balasnest** [comment] 2018-10-08 09:15
@georgian3688 No. I am still facing this problem. Lets wait for this fix.

**Comment by Balasnest** [comment] 2018-10-11 06:40
@iThink32 @umanghome I have tired integrating completely with new project. Its still reproducing this. Please check this link.
http://recordit.co/ewVorNgqS6

Tested with demo creds:
**Domestic** 
```
_Mastercard_
5104_0155_5555_5558,  **not working until retry**
5104_0600_0000_0008  **not working until retry**
_Visa_ 
4111_1111_1111_1111 **not working until retry**
```

**International**
```
_Mastercard_
5555_5555_5555_4444,   _International cards are not allowed_
5105_1051_0510_5100  _International cards are not allowed_

_Visa_ 
 4012_8888_8888_1881,  _International cards are not allowed_
4000_1841_8621_8826  **Only this works!**
```

**Comment by georgian3688** [comment] 2018-10-12 10:58
@iThink32  any updates, Is it fixed ? I am waiting for this fix.

**Comment by AbhinavArora95** [comment] 2018-10-15 07:30
Hi, we are actively looking into the issue. We are working on a solution which might involve a new sdk release. We will update you once we fix this issue.

**Comment by georgian3688** [comment] 2018-10-16 09:43
@AbhinavArora95  Sure, thanks for the response.

**Comment by sagar1garg** [comment] 2018-10-26 04:29
@AbhinavArora95 is the issue fixed?

**Comment by Balasnest** [comment] 2018-11-02 12:49
@AbhinavArora95 @iThink32  Any updates on this?

**Comment by iThink32** [comment] 2018-11-02 13:01
@Balasnest we are still working on this issue , we will update you when the issue gets fixed.

**Comment by georgian3688** [comment] 2018-11-28 09:02
@Balasnest Are you able to resolve the issue ? @AbhinavArora95  any updates? Its too long time since opened the issue, still I can't see any progress.  If the issue will be there forever, sorry to say I have to move to some other payment library.

**Comment by mynkgrwl** [comment] 2018-11-28 10:13
Can anyone provide any work around for this issue ?
We have a release planned in next month.

**Comment by AbhinavArora95** [comment] 2018-11-28 10:18
@georgian3688 @sagar1garg As we are unable to reproduce the issue, we are working with @Balasnest to get it resolved.

Meanwhile can you all please try Razorpay Sample App - and let me know if you are facing the same issue with the sample app also . -https://play.google.com/store/apps/details?id=com.razorpay.newsampleapp

Also, please specify if the issue is with specific devices or with all devices?

**Comment by mynkgrwl** [comment] 2018-11-28 10:47
I was facing the same issue but it was reproducing on emulator only.
On actual device it worked for me.

**Comment by Balasnest** [comment] 2018-11-28 10:53
@AbhinavArora95  Installed from [playstore app](https://play.google.com/store/apps/details?id=com.razorpay.newsampleapp) and tried with **oneplus one device (6.0.1)**.  Still can reproduce the issue.

**Comment by Balasnest** [comment] 2018-11-30 08:34
@sumedht 
According to my testing:

 **Not worked with these devices:**
1. oneplus one  - 6.0.1
2. Nexus 5 - 7.1.1 (_emulator_)
3. Samsung S5 - 4.4

**Worked with these devices:**
1. Google Pixel 2 XL - 9 (_emulator_)
2. Mi 4A - 7.1.2

**Comment by Balasnest** [comment] 2018-12-05 06:43
@sumedht @umanghome @AbhinavArora95 Guys Are there any updates regarding this? Are you able to reproduce?

**Comment by sumedht** [comment] 2018-12-05 07:10
@Balasnest We have updated react-native version. Can u check with the latest version

**Comment by Balasnest** [comment] 2018-12-06 07:31
@sumedht  Latest version of RZP needs **react native 0.57.0** and Xcode 10. 

Already we had upgraded the react native version from 0.51 to 0.56 and integrated with **RZP 2.0.9 | 2.0.10**. But it was not working.

We checked with [Razorpay sample App](https://play.google.com/store/apps/details?id=com.razorpay.newsampleapp) and issues were exists.

If we need to check with RZP >=2.0.13, then we need to move to react native 0.57.0. This will be another long process for us right now.

We need some fixes to be done which is compatible to react native version. Waited for so long, Please fix this as soon as possible.

**Comment by Balasnest** [comment] 2018-12-19 12:11
@umanghome  Please reopen this issue.  We haven't got the solution for this problem.

**Comment by sumedht** [comment] 2018-12-20 07:44
> @sumedht Latest version of RZP needs **react native 0.57.0** and Xcode 10.
> 
> Already we had upgraded the react native version from 0.51 to 0.56 and integrated with **RZP 2.0.9 | 2.0.10**. But it was not working.
> 
> We checked with [Razorpay sample App](https://play.google.com/store/apps/details?id=com.razorpay.newsampleapp) and issues were exists.
> 
> If we need to check with RZP >=2.0.13, then we need to move to react native 0.57.0. This will be another long process for us right now.
> 
> We need some fixes to be done which is compatible to react native version. Waited for so long, Please fix this as soon as possible.

@Balasnest We have fixed this issue and it's updated in v2.0.17. We are using react-native version 0.57 for the build compatible with Xcode 10, so can not roll back to below that version.

**Comment by sumedht** [comment] 2018-12-20 07:45
> +1
> facing the same issue on android
> used library version: 2.0.9

@meghaptg We have fixed this issue in update v2.0.17

**Comment by sumedht** [comment] 2018-12-20 07:47
> @Balasnest @meghaptg Did you manage to get it work?
> @umanghome @iThink32 Any solution for this ? I am still facing the same issue in android only. I have checked in ios (it is working fine).

@georgian3688 We have fixed this issue in v2.0.17

**Comment by georgian3688** [comment] 2018-12-21 05:19
@sumedht thanks a lot, will check with latest version. I am using **react native 0.54.0**. Will it work on this?

**Comment by iThink32** [comment] 2019-01-30 07:20
closing due to inactivity,reopen if required.

**Closed by iThink32** 2019-01-30 07:20 UTC

**Comment by NxsHbb** [comment] 2021-09-09 07:07
Facing similar issue in 2021
