### ISSUE TITLE
Image is not rendering from firebase

### ISSUE THREAD

**Issue by hackrx** [razorpay/react-native-razorpay#305] opened 2020-11-24 14:40 UTC
## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest React Native Razorpay plugin release to make sure your issue has not already been fixed. 

 
## Razorpay Package Version :
Open `Package.json`. > Copy `react-native-razorpay` "^2.2.1"
 
 

## Java and Gradle Version (android) :
Specify your Java and Gradle version.
```
buildToolsVersion = "29.0.3"
        minSdkVersion = 19 // updating from 16 to 19 due to razorPay
        compileSdkVersion = 30
        targetSdkVersion = 30
         supportLibVersion = "28.0.0"
```

### What you did:
I am trying to display a user image in the image box, but it is not rendering the image
![image](https://user-images.githubusercontent.com/54453778/100107271-7d296d00-2e8f-11eb-86bf-e9a49474491d.png)

The firebase storage URL to the image looks like:  `https://firebasestorage.googleapis.com/v0/b/mytestApp.appspot.com/o/images%2FpZm8daajsIS4LvqBYTiWiuLIgmE2?alt=media&token=3kuli4cd-dc45-7845-b87d-5c4acc7da3c2`
Note: I have modified the URL, due to a private project.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.Upload an image to firebase storage, then copy the image link with token 
2.Pass this link as an image parameter.

## Code example, screenshot, or link to a repository:

```
let options = {
            description: 'User : Test User',
            image: photo,                                        //<----------firebase image with token
            currency: 'INR',
            key: '<MyKey>',
            amount: 100,
            name: 'My corp',
            prefill: {
              email: props.emailId,
              contact: props.phoneNumber,
              name: props.displayName,
            },
            theme: {color: 'green'},
          };
```

Any help with this issue would be appreciated.

**Comment by hackrx** [comment] 2020-12-04 11:20
@Nautiyalsachin @captn3m0 @hariramsvnit @sumedht guys can anyone of you help me with this issue?
you can take `https://firebasestorage.googleapis.com/v0/b/hostel-life-70814.appspot.com/o/example%2Fpexels-kevin-bidwell-3863793.jpg?alt=media&token=d910dfd3-cf15-47b9-8b36-e3dffdad652a` as an example `image` URL.
Any help would be appreciated.

**Comment by Nautiyalsachin** [comment] 2020-12-15 06:55
Hi @hackrx, we are looking into this, we will let you know once this is fixed.

**Comment by Nautiyalsachin** [comment] 2020-12-15 07:38
@hackrx, the above link is not working, can you provide a new URL which we can use for validation, or else this issue will be closed.

**Comment by hackrx** [comment] 2020-12-15 07:39
Yeah sure, please wait

**Comment by Nautiyalsachin** [comment] 2020-12-15 07:50
It's rendering correctly, just validated. 
![Simulator Screen Shot - iPhone 11 - 2020-12-15 at 13 18 50](https://user-images.githubusercontent.com/14342956/102186065-14567300-3ed8-11eb-8919-f06ed8e3f16c.png)

Here in above links - 

This link is not valid - 'image' : 'https://firebasestorage.googleapis.com/v0/b/mytestApp.appspot.com/o/images%2FpZm8daajsIS4LvqBYTiWiuLIgmE2?alt=media&token=3kuli4cd-dc45-7845-b87d-5c4acc7da3c2',

This is working - 'image' : 'https://firebasestorage.googleapis.com/v0/b/hostel-life-70814.appspot.com/o/example%2Fpexels-kevin-bidwell-3863793.jpg?alt=media&token=d910dfd3-cf15-47b9-8b36-e3dffdad652a',

**Comment by hackrx** [comment] 2020-12-15 07:55
Okay, let me check and verify then I will close this issue.
Thanks.

**Comment by hackrx** [comment] 2020-12-16 06:46
Hey @Nautiyalsachin, it is working fine on iOS:
![image](https://user-images.githubusercontent.com/54453778/102314440-74ace980-3f98-11eb-9542-0cd7f95ac1e4.png)
Please solve this issue for android.
Thanks.

**Comment by Nautiyalsachin** [comment] 2020-12-16 08:05
@hackrx Can you share the URL you are using for Android?

**Comment by hackrx** [comment] 2020-12-16 08:08
[link](https://firebasestorage.googleapis.com/v0/b/hostel-life-70814.appspot.com/o/example%2Fpexels-kevin-bidwell-3863793.jpg?alt=media&token=d910dfd3-cf15-47b9-8b36-e3dffdad652a)
you can use this image url, it is also not working for me.

**Comment by Nautiyalsachin** [comment] 2020-12-16 08:11
Can you try reducing the image size first?

**Comment by hackrx** [comment] 2020-12-16 08:17
[link](https://firebasestorage.googleapis.com/v0/b/hostel-life-70814.appspot.com/o/example%2Fcat.jpg?alt=media&token=743f799d-19e8-4464-b67d-a29e3ca93e08)
this is the image link

**Comment by hackrx** [comment] 2020-12-22 09:25
@Nautiyalsachin can you please review this issue, this is causing a delay in the app release.
Thanks.

**Comment by Nautiyalsachin** [comment] 2021-01-25 07:11
@hackrx We are not able to reproduce this issue on our side. Please give more details. We suggest you to use some simple URLs for rendering the images. Most likely that will solve this issue. 

For now closing this issue, feel free to add more comments here or re-opening this.
Thanks.

**Closed by Nautiyalsachin** 2021-01-25 07:11 UTC
