### ISSUE TITLE
Submit to App Store issues: Unsupported Architecture x86

### ISSUE THREAD

**Issue by malangaveuday** [razorpay/react-native-razorpay#60] opened 2018-02-24 03:48 UTC
![screen shot 2018-02-24 at 1 05 55 am](https://user-images.githubusercontent.com/12609892/36625300-fd565e58-1942-11e8-97c5-787382eec85e.png)

iTunes store throws the error when tried to upload archive build from Xcode.

**Comment by AbhinavArora95** [comment] 2018-02-26 08:16
@malangaveuday - When a framework is distributed, it contains architectures of the simulators so that the consumer of the framework can built it on a simulator. However, when you are uploading the archive on itunes, you have to strip these architectures. If you would have been using cocoapods, it would have been done by it. Since, probably you are not using it, please run the attached script on the Razorpay.framework within your archive or before create the archive.
[StripInvalidArchitectures.txt](https://github.com/razorpay/react-native-razorpay/files/1757670/StripInvalidArchitectures.txt)

**Comment by rishiankush** [comment] 2019-03-07 07:12
@AbhinavArora95  Thanks for the solution. you saved my day!

**Comment by mukulkumar1703** [comment] 2019-05-31 06:22
@AbhinavArora95  
I am also getting the same error while uploading the build in app store. I copied the script from "StripInvalidArchitectures.txt" file that you have shared above and put it on the Build Phases/ Run Script and archive the build, but now I am getting following error

fatal error: lipo: can't open input file: Razorpay.framework/Razorpay (No such file or directory)
fatal error: lipo: can't open input file: Razorpay.framework/Razorpay (No such file or directory)
rm: Razorpay.framework/Modules/Razorpay.swiftmodule/i386.swiftdoc: No such file or directory
rm: Razorpay.framework/Modules/Razorpay.swiftmodule/i386.swiftmodule: No such file or directory
rm: Razorpay.framework/Modules/Razorpay.swiftmodule/x86_64.swiftdoc: No such file or directory
rm: Razorpay.framework/Modules/Razorpay.swiftmodule/x86_64.swiftmodule: No such file or directory

Please let me know what I am doing wrong here

Thanks

**Comment by pronav** [comment] 2019-05-31 07:27
Have you included `Razorpay.framework` in embed binaries step?

**Comment by mukulkumar1703** [comment] 2019-05-31 09:47
@pronav  yes I have in included, but now I am able to upload the build in apple store.

**Comment by mathewk2017** [comment] 2019-06-24 05:51
@mukulkumar1703  how did you solved the problem? I am getting the same error.

**Comment by Biplovkumar** [comment] 2019-08-28 07:28
> framework

in which folder, we need to run command. Plz share !
![Screenshot 2019-08-28 at 12 57 39 PM](https://user-images.githubusercontent.com/30401136/63834658-7150b180-c993-11e9-95cf-c194ba06dcd9.png)


I have these valid architecture , Do need to run that command.

**Comment by Anujmoglix** [comment] 2020-01-03 12:09
I am also facing this issue . Any solution for this ?

**Comment by iamromec** [comment] 2020-03-18 19:33
@AbhinavArora95 I am not a Swift developer and I don't understand, "Locate the directory in which Razorpay.framework is present in the archive that you are trying to upload."

Could you please share specific steps? Also this FAQ step couldn't help: https://razorpay.com/docs/payment-gateway/ios-integration/faq/

I couldn't find the directory where Razorpay.framework is localited.

**Comment by Nautiyalsachin** [comment] 2020-03-19 07:47
Hi @iamromec : Can you give me more details about this, Also it will help if you can add some logs or screenshots.

**Comment by iamromec** [comment] 2020-03-19 07:50
Sure. I've followed the FAQ and some other unlisted video to fix this but yet couldn't.

I have attached a couple of screenshots.
![Screenshot 2020-03-19 at 10 58 58 AM](https://user-images.githubusercontent.com/50284628/77043856-61a6c200-69e4-11ea-940c-0d1db1dc775c.png)
![Uploading Screenshot 2020-03-19 at 10.51.09 AM.png…]()

![Screenshot 2020-03-19 at 11 14 57 AM](https://user-images.githubusercontent.com/50284628/77043832-56ec2d00-69e4-11ea-9b31-efcbc9386b7a.png)

**Comment by iamromec** [comment] 2020-03-19 07:51
@Nautiyalsachin here's the video link I was asked to follow: https://www.youtube.com/watch?v=HVGUBRot7VA&feature=youtu.be but didn't work.

**Comment by iamromec** [comment] 2020-03-19 07:56
I'm using 

IONIC Version: 5.0.0
XCode Version: 11.3
Razorpay Cordova Plugin Version: 1.4.8

**Comment by Nautiyalsachin** [comment] 2020-03-19 08:02
Can you tell me the steps, how you try to install the Razorpay plugin?

**Comment by iamromec** [comment] 2020-03-19 08:05
To install the plugin, I used:

ionic cordova plugin add com.razorpay.cordova

And then 

ionic cordova build ios --prod

Then went to platforms/ios and clicked on .xcworkspace.

**Comment by Nautiyalsachin** [comment] 2020-03-19 08:38
I guess you are using Angular, as you have mentioned Cordova in the question, and for future references please raise the issue in [Razorpay Cordova](https://github.com/razorpay/razorpay-cordova) repository.

1. Try removing the current package and

2. Use `cordova plugin add https://github.com/razorpay/razorpay-cordova.git`

We are updating our cordova package soon. For now, you can install it directly from github. 

Let me know if it works for you.

**Comment by iamromec** [comment] 2020-03-19 08:50
2. Use cordova plugin add https://github.com/razorpay/razorpay-cordova.git

This seems to be broken. I'm unable to install with this. It just stuck here only.

![Screenshot 2020-03-19 at 2 19 53 PM](https://user-images.githubusercontent.com/50284628/77048625-c108d000-69ec-11ea-94fd-4a7177a05a07.png)

**Comment by iamromec** [comment] 2020-03-19 08:54
Do I still need to add that script?

**Comment by Nautiyalsachin** [comment] 2020-03-19 08:55
Can you create a new project and try again. It's working for me here, 

<img width="501" alt="Screenshot 2020-03-19 at 2 24 58 PM" src="https://user-images.githubusercontent.com/14342956/77049059-6b80f300-69ed-11ea-9e99-d422975533f2.png">

Also no need for the script and any extra step.

**Comment by iamromec** [comment] 2020-03-19 09:13
Ah! Man. With this, it conflicts with other plugins within the project. Like GooglePlus.

When I removed it and re-added the platform, it works fine. But not with the `cordova plugin add https://github.com/razorpay/razorpay-cordova.git`

![Screenshot 2020-03-19 at 2 33 09 PM](https://user-images.githubusercontent.com/50284628/77050529-e9de9480-69ef-11ea-8c0c-7e77d5d33860.png)

**Comment by iamromec** [comment] 2020-03-19 09:34
@Nautiyalsachin are you looking into?

**Comment by Nautiyalsachin** [comment] 2020-03-19 09:41
This is an iOS related issue. Follow the steps mentioned in this [link](https://github.com/razorpay/react-native-razorpay/issues/60#issuecomment-601079281), also please try to google the issues you face. Sometime you might get lucky there.

**Comment by iamromec** [comment] 2020-03-19 09:48
It isn't. It's occurring when I install the plugin with the URL you've mentioned. If I remove it, it works fine so it should be something with it I guess. 

You are testing with sample project but in reality, there won't be a project just with only Razorpay plugin.

**Comment by iamromec** [comment] 2020-03-19 09:51
Why would I post here if I could just find it on Google? I did and sent you all the resources I find related to this. Even I've followed what your official docs say.

**Comment by Nautiyalsachin** [comment] 2020-03-19 10:04
@iamromec : As I can't see anything related to Razorpay, I won't be able to resolve this issue here, you can try it by searching in Google plus repositories for more details.

**Comment by iamromec** [comment] 2020-03-19 10:07
@Nautiyalsachin 

What? Everything is working smoothly without the plugin with URL you've specified and when I do this, it creates conflicts and you're talking that it's not related to Razorpay? How so?

It works fine even with the existing plugin command cordova plugin add com.razorpay.cordova and just the problem is with the archive file. 

Why are you not getting the point that it's obviously related to Razorpay?

**Comment by Nautiyalsachin** [comment] 2020-03-19 10:21
Okay, try adding the script again as I can see the simulator architecture in that. It will help you to archive the Google Plus framework.

**Comment by iamromec** [comment] 2020-03-19 10:23
Yeah but I'm unable to succeed with `ionic cordova build ios` command. Once it's done, then I could proceed with opening the .xsworkspace file and add the script.

**Comment by Nautiyalsachin** [comment] 2020-03-19 10:36
Have you already added the script?

**Comment by iamromec** [comment] 2020-03-19 10:43
No.

**Comment by iamromec** [comment] 2020-03-19 10:44
Is it possible for you to take this on TeamViewer?

**Comment by Nautiyalsachin** [comment] 2020-03-19 11:24
So, you are able to archive ?

**Comment by iamromec** [comment] 2020-03-19 11:26
Noooo, that's the problem. I'm seeing this error I've sent you via screenshots in the email when the validation part completes or distributing to the appstore.

![Screenshot 2020-03-19 at 11 14 57 AM](https://user-images.githubusercontent.com/50284628/77062776-8f026880-6a02-11ea-8399-f8ad8033c3fa.png)

**Comment by iamromec** [comment] 2020-03-19 11:28
The build is working on the simulator...it's just when distributing to the app store, it gives this error. I think you missed some parts of the problem which I've sent in the starting.

**Comment by Nautiyalsachin** [comment] 2020-03-23 10:33
Closing this issue as this is resolved.

**Closed by Nautiyalsachin** 2020-03-23 10:33 UTC
