### ISSUE TITLE
BUG: razorpay crash

### ISSUE THREAD

**Issue by evolvingkid** [razorpay/react-native-razorpay#413] opened 2022-08-22 06:23 UTC
## Description
Razorpay randomly crash for a user. We weren't able to reproduce the crash. This was only happen to android device.

The crash log was:
```
Fatal Exception: java.lang.NoSuchFieldError: No static field activity_result_invalid_parameters of type I in class Lcom/razorpay/R$string; or its superclasses (declaration of 'com.razorpay.R$string' appears in /data/app/com.tortoisehq.tortoise-ZxeRTNLGKeuEgqbhf3KR_A==/base.apk!classes3.dex)
       at com.razorpay.CheckoutPresenterImpl.setOptions(CheckoutPresenterImpl.java:186)
       at com.razorpay.b__J_.onCreate(BaseCheckoutActivity.java:107)
       at com.razorpay.BaseCheckoutOtpelfActivity.onCreate(BaseCheckoutOtpelfActivity.java:26)
       at com.razorpay.CheckoutActivity.onCreate(CheckoutActivity.java:8)
       at android.app.Activity.performCreate(Activity.java:7009)
       at android.app.Activity.performCreate(Activity.java:7000)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

## Razorpay Package Version :
"react-native-razorpay": "^2.2.9",
 

## Java and Gradle Version (android) :
Specify your Java and Gradle version.
openjdk 11.0.15 2022-04-19 LTS

Gradle 6.7
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.
2.

## Code example, screenshot, or link to a repository:
Please provide a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by kkyusufk** [comment] 2022-08-30 18:11
Hey @evolvingkid, please let us know if this issue is still existing as well a step to reproduce.

**Comment by evolvingkid** [comment] 2022-09-11 09:37
We only had this issues one time and we weren’t able to reproduced

**Comment by kkyusufk** [comment] 2022-09-11 21:14
@evolvingkid Thanks for the update.
We are closing this issue since its not re-produceable but please re-open it if you encounter this issue again.

**Closed by kkyusufk** 2022-09-11 21:14 UTC

**Comment by ils-nazirh** [comment] 2025-08-29 12:02
Encountered the same crash in out app. app gets crash with in a second after launch.

### Stack Trace:
```
Fatal Exception: java.lang.NoSuchFieldError: No field activity_result_invalid_parameters of type I in class Lcom/razorpay/R$string; or its superclasses (declaration of 'com.razorpay.R$string' appears in /data/app/~~qLDIiXUnxP-b-Fk4MajOSw==/com.myapp.app-UfhMLXMhRZ4EKu-7qeySYQ==/base.apk!classes2.dex)
       at com.razorpay.CheckoutPresenterImpl.setOptions(CheckoutPresenterImpl.java:288)
       at com.razorpay.BaseCheckoutActivity.onCreate(BaseCheckoutActivity.java:122)
       at com.razorpay.BaseCheckoutOtpelfActivity.onCreate(BaseCheckoutOtpelfActivity.java:25)
       at com.razorpay.CheckoutActivity.onCreate(CheckoutActivity.java:8)
       at android.app.Activity.performCreate(Activity.java:7994)
       at android.app.Activity.performCreate(Activity.java:7978)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1548)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3406)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3607)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2068)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7680)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:423)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

### Device
Brand: OnePlus
Model: OnePlus8Pro
Orientation: Portrait
RAM free: 2.27 GB
Disk free: 2.48 GB

Operating System: Android 11

Crash Date: Aug 13, 2025, 9:58:12 PM

### Package version:

react-native: 0.75.5
react-native-razorpay: 2.3.0
