### ISSUE TITLE
UPI option is not visible

### ISSUE THREAD

**Issue by jayeshpurohit12** [razorpay/react-native-razorpay#464] opened 2023-12-17 09:38 UTC
<img width="321" alt="Screenshot 2023-12-17 at 3 06 18 PM" src="https://github.com/razorpay/react-native-razorpay/assets/61271857/1d8c4ec9-9ae4-4d8d-b13e-ec39510b20c0">

### I am using latest version of react native

**Comment by vivekshindhe** [comment] 2023-12-18 05:52
@jayeshpurohit12 2 queries, 
1. Can you try to reload checkout and see if this is still an issue? 
2. Is the method UPI enabled for the merchant ID you are using? 

Would be helpful if you could share the MID and the options payload you are using to load checkout.

**Comment by jayeshpurohit12** [comment] 2023-12-18 06:03
@vivekshindhe 

MID: GyHQlvic5Q3fik
Upi is enabled for the merchant ID that we are using, 
options that we are using is something like that 

{
        description: 'test desc',
        image: '',
        currency: 'INR',
        key: Config.RAZORPAY_KEY,
        amount: subscriptionPrice,
        name: priceId.planType,
        order_id: orderId,
        prefill: {
          email: parentDetails.email,
          contact: parentDetails.phoneNumber,
          name: parentDetails.firstName + ' ' + parentDetails.lastName,
        },
        theme: {color: Colors.brandPrimary.default},
      };

**Comment by vivekshindhe** [comment] 2023-12-18 06:17
@jayeshpurohit12 thank you for the details. Would it also be possible to send a couple of order_ids for us to test? It will help us replicate the issue.

**Comment by jayeshpurohit12** [comment] 2023-12-18 07:19
@vivekshindhe 

here are some order ids

order_NDMhKYvGmCbXBe
order_NDMfJGejaY2QBM
order_NDM5dgPC5ZIstH

**Comment by vivekshindhe** [comment] 2023-12-18 07:49
@jayeshpurohit12 From our inquiry, we see that the MID you shared with us does not have method UPI enabled for either collect or intent requests. Requesting you to re-verify the enablement for the MID shared with us. Since this is related to the account itself and not react-native-razorpay, if you can see the method as enabled, I would request you to raise the ticket on the Razorpay Dashboard. Closing this ticket

**Closed by vivekshindhe** 2023-12-18 07:49 UTC

**Comment by jayeshpurohit12** [comment] 2023-12-18 07:56
@vivekshindhe I have double checked that upi enabled one and it is enabled, okay so I will raise the ticket on the Razorpay Dashboard

**Comment by mahipalsingh7** [comment] 2024-05-05 17:23
@vivekshindhe 
I am also facing the same issue. UPI option is not displaying on payment page.

**Comment by HazSyl1** [comment] 2024-05-10 18:23
Hi, I'm having the same issue. How did you guys fix it? Also, how do I check if UPI is enabled or not?

**Comment by vivekshindhe** [comment] 2024-05-15 08:11
Hey folks, UPI Intent payments are not enabled by default for live keys. If you aren't seeing UPI intent flow on the Checkout Page, please create a ticket on your Razorpay Dashboard and Razorpay's Support Team will be able to help you out in a quick timeframe.

**Comment by HazSyl1** [comment] 2024-05-15 08:31
> Hi, I'm having the same issue. How did you guys fix it? Also, how do I check if UPI is enabled or not?

Update: I got my account verified (kyc done). The live mode can be enabled now . And now it showed the option for QR UPI payments . So I guess you need to get your kyc done for using UPI.

**Comment by anirudhsama** [comment] 2025-02-21 04:45
@vivekshindhe UPI Intent flow is working for one time payments, but it isn't working for recurring payments (subscriptions). We have raised a ticket with support and they have confirmed that intent flow is enabled for recurring payments as well. Is there something we are missing?
