### ISSUE TITLE
Getting success callback event for failed payment

### ISSUE THREAD

**Issue by ayusch-apps-curefit** [razorpay/react-native-razorpay#249] opened 2020-02-24 09:26 UTC
* **Common to Both platforms :-**

  - [x] I have gone through the README (https://github.com/razorpay/react-native-razorpay)
  - [x] I have searched for a similar issue (https://github.com/razorpay/react-native-razorpay/issues)
  - [x] I am using the latest version of our framework (https://github.com/razorpay/react-native-razorpay/releases)
  - [x] I have cleaned my project.
  - [ x I have gone through FAQ's (https://github.com/razorpay/react-native-razorpay/wiki/FAQ's)

* **Specific to iOS Users :-**

  - [x] I have modified the module map as specified in the readme (https://github.com/razorpay/react-native-razorpay)
  - [x] I have deleted the contents of the derived data folder and rebuild it.

Receiving multiple success callbacks. Payment fails once, but the next time it's successful we receive two success callbacks.

## IDE Specs
IDE: WebStorm (React Native).
Razorpay SDK Version: 2.1.31

## Retro Steps
1. Initiate a payment. (Razorpay's bottom sheet opens up).
2. Cancel the payment.
3. Wait for approx. 1 hour.
4. Initiate the payment again and mark successful.

**Comment by Nautiyalsachin** [comment] 2020-02-24 10:20
Hi @ayusch-apps-curefit, can you provide more details here? Like the response of success callbacks and how to reproduce it.

**Comment by ayusch-apps-curefit** [comment] 2020-02-24 10:28
I've already mentioned the steps to reproduce it (Retro Steps). 
Also, there isn't any specific response from the callbacks. I guess that the old callback subscription isn't getting removed somehow leading to multiple success callbacks from SDK.

**Comment by Nautiyalsachin** [comment] 2020-02-24 10:44
@ayusch-apps-curefit, have you tried updating current SDK to v2.1.32. As we have updated our package and provided support for AutoLink.

**Comment by ayusch-apps-curefit** [comment] 2020-02-24 10:46
Will it also address the problem above?

**Comment by Nautiyalsachin** [comment] 2020-02-24 10:58
I think so, as we have modified the current package.

**Comment by Nautiyalsachin** [comment] 2020-03-09 07:15
Closing this issue due to the time elapsed. Please feel free to either re-open the issue or create a
new issue if you have any additional queries.

**Closed by Nautiyalsachin** 2020-03-09 07:15 UTC
