### ISSUE TITLE
Getting error undefined | undefined while calling RazorpayCheckout.open

### ISSUE THREAD

**Issue by Abhi0059** [razorpay/react-native-razorpay#334] opened 2021-05-19 08:48 UTC
it was working fine before...suddenly i am getting error undefined | undefined while calling RazorpayCheckout.open .. i didn't change anything... i was using react-native-razorpay:2.2.2 and googled about this issue.. some says to update it . so i did react-native-razorpay:2.2.5 but still getting same issue... please help me out.. thanks in advance.
 
var options = {
                      description: 'Credits towards consultation',
                      image: 'https://i.imgur.com/3g7nmJC.png',
                      currency: 'INR',
                      key: 'xxxxxxx',
                      amount: `${amount}00`,
                      name: userName,
                      order_id: 'order_1',
                      prefill: {
                        email: userEmail,
                        contact: userPhone,
                        name: userName,
                      },
                      theme: {color: '#6699ff'},
                    };
                    RazorpayCheckout.open(options)
                      .then((data) => {
                        alert(
                          `Success: ${data.razorpay_payment_id} `,
                        );
                      })
                      .catch((error) => {
                        alert(`Error: ${error.code} | ${error.description}`);
                      });
                  }

**Comment by sumedht** [comment] 2021-05-24 04:35
@Abhi0059 Getting this issue on iOS or Android? Looks like lib is not imported properly so it's not able to get related classes & hence giving undefine as an error.

**Comment by Abhi0059** [comment] 2021-05-24 14:49
i am working on android .. i think it is imported properly because my payments are going to admin panel(razorpay).

**Comment by vivekshindhe** [comment] 2021-05-24 18:38
Could you create a sample project where you are able to produce this error and send the same to us? That would be really helpful. The information provided isn't much to go on, and the issue isn't reproducible by us. 

Thanks.

**Comment by Abhi0059** [comment] 2021-05-25 07:19
@vivekshindhe ok

**Comment by Abhi0059** [comment] 2021-05-29 07:27
Hi @vivekshindhe i created a sample project where i am getting same issue... where i have to send ?

**Comment by vivekshindhe** [comment] 2021-05-29 14:47
Please send it at vivek.shindhe@razorpay.com

**Comment by Abhi0059** [comment] 2021-05-30 07:16
Hi @vivekshindhe Please check sample project at vivek.shindhe@razorpay.com

**Comment by vivekshindhe** [comment] 2021-05-31 14:16
@Abhi0059 I just checked the project you shared and it's working just fine. Please try completely uninstalling and cleaning cache before reinstalling and trying this again.

**Comment by Abhi0059** [comment] 2021-06-01 05:23
Hi @vivekshindhe, i run that same code on 3 different android devices.. but still getting same error.. did you checked with same API key which i shared to you?

**Comment by vivekshindhe** [comment] 2021-06-01 05:41
@Abhi0059 Yes. I didn't change anything. 
- npm install
- npx react-native run-android
And it worked.

**Comment by Abhi0059** [comment] 2021-06-01 06:47
@vivekshindhe i also tried making build for 2 different Systems ... mac and windows but still getting same.. can you please help me out via skype, phone call, google meet any which ever suitable for you.

**Comment by vivekshindhe** [comment] 2021-06-01 09:54
@Abhi0059 Sure. Let's connect over a call. Could you please send your email-address that is registered with Razorpay and your Merchant ID to vivek.shindhe@razorpay.com so we can set up this call? Thank you for your patience.

**Comment by Abhi0059** [comment] 2021-06-01 12:51
@vivekshindhe Thanks .. finally i got the issue.. now it is working fine.

**Comment by vivekshindhe** [comment] 2021-06-01 13:14
@Abhi0059 Could you please explain what the issue was?? This may help people with the same issue in the future. 

Also, closing the issue. Please feel free to open another one if needed.

Thank you.

**Closed** 2021-06-01 13:14 UTC

**Comment by Abhi0059** [comment] 2021-06-01 15:44
Yes @vivekshindhe , the code which i sent you.. i was alerting "${amount}" in (alert(`Success: ${data.razorpay_payment_id} ${amount}`))  which was the issue..here amount is not defined.. so it goes to catch block.. but don't know how it was running at your end.

**Comment by vivekshindhe** [comment] 2021-06-01 18:30
I had changed that after seeing there was no variable in that name guessing there was some different code that was missing when creating the sample project. Glad you were able to resolve your issue.

**Comment by Vishal3474** [comment] 2023-02-23 06:51
Can You Send Screenshot

**Comment by SanjibanRoy** [comment] 2024-11-01 15:22
> I had changed that after seeing there was no variable in that name guessing there was some different code that was missing when creating the sample project. Glad you were able to resolve your issue.

i have same issue. If possible can you help. With EXPO

    var options = {
        description: 'Credits towards consultation',
        image: 'https://i.imgur.com/3g7nmJC.jpg',
        currency: 'INR',
        key: 'rzp_test_',
        amount: '100',
        name: 'Acme Corp',
        order_id: 'dsd',//Replace this with an order_id created using Orders API.
        prefill: {
          email: 'gaurav.kumar@example.com',
          contact: '9191919191',
          name: 'Gaurav Kumar'
        },
        theme: {color: '#53a20e'}
      }
      RazorpayCheckout.open(options).then((data) => {
        console.log(data)
        console.log(`Success`);
      }).catch((error) => {
        console.error(`Error: ${error.code} | ${error.description}`);
      });
