### ISSUE TITLE
Bundle error

### ISSUE THREAD

**Issue by crushy26** [razorpay/react-native-razorpay#138] opened 2018-11-23 10:27 UTC
react: "16.6.1",
 react-native: "0.57.5",
 react-native-razorpay: "^2.0.14",

I am trying to integrate razorpay into exisiting RNN project, getting the following error on react-native run-android, Please help.

> error: bundling failed: Error: jest-haste-map: Haste module naming collision:
>   Duplicate module name: react-native
>   Paths: /Users/crushy/edt/node_modules/react-native/package.json collides with /Users/crushy/edt/node_modules/react-native-razorpay/node_modules/react-native/package.json
> 
> This error is caused by `hasteImpl` returning the same name for different files.
>     at setModule (/Users/crushy/edt/node_modules/jest-haste-map/build/index.js:551:17)
>     at workerReply (/Users/crushy/edt/node_modules/jest-haste-map/build/index.js:613:9)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by iThink32** [comment] 2018-11-23 10:37
@crushy26 first make sure you'r using the latest version of react-native-razorpay , after which if you still find node modules in the react-native-razorpay package delete it.

**Comment by crushy26** [comment] 2018-11-23 10:56
Hi @iThink32, thank you for the quick reply. I managed to make it work by blacklisting the RN in metro bundler.

**Comment by iThink32** [comment] 2018-11-23 11:48
@crushy26 that will also do but ideally speaking you can delete the node-modules folder in react-native-razorpay we are not referencing it from there

**Comment by iThink32** [comment] 2018-11-23 11:48
closing as the issue is fixed.

**Closed by iThink32** 2018-11-23 11:48 UTC
