### ISSUE TITLE
Unknown type name 'RazorpayCheckout'; did you mean 'RNRazorpayCheckout'?

### ISSUE THREAD

**Issue by sivaLeo** [razorpay/react-native-razorpay#331] opened 2021-05-11 17:55 UTC
Look at the screenshot.

"react-native": "0.61.5",
"react-native-razorpay": "2.2.4",

## Screenshots 
<img width="1183" alt="Screenshot 2021-05-11 at 11 08 15 PM" src="https://user-images.githubusercontent.com/61038578/117861808-7bbdf680-b2af-11eb-91de-b4eb665f7564.png">

**Comment by sivaLeo** [comment] 2021-05-11 17:56
what is missed

**Comment by Nautiyalsachin** [comment] 2021-05-12 05:43
Hi @sivaLeo, try removing the plugin and adding it again, also recommend you to run `pod update` from the iOS folder.

**Comment by vineeth-vk11** [comment] 2021-05-12 06:46
@Nautiyalsachin  I am also facing the same issue from yesterday

**Comment by sivaLeo** [comment] 2021-05-12 06:46
i tried already
npm uninstall --save react-native-razorpay
cd ios && pod install && cd ..
npm install --save react-native-razorpay
cd ios && pod install && cd ..


------Not working-----

**Comment by vineeth-vk11** [comment] 2021-05-12 06:51
@sivaLeo are you using the latest M1 mac with latest xcode?

**Comment by sivaLeo** [comment] 2021-05-12 06:56
@vineeth-vk11 
i'm using MacBook Pro MacOS 10.15.6
Xcode Version 12.4 (12D4e)

**Comment by vineeth-vk11** [comment] 2021-05-12 07:02
@sivaLeo I am able to build the code successfully in debug build configuration but the build fails in production build configuration. Are you able to build in debug config?

**Comment by sivaLeo** [comment] 2021-05-12 07:05
I got stuck in debug mode

**Comment by Nautiyalsachin** [comment] 2021-05-12 07:27
@vineeth-vk11 Try changing **Build Active Architecture Only** to **Yes** for both **release** and **debug**. Also see our [FAQs](https://github.com/razorpay/react-native-razorpay/wiki/FAQ's) for more details.

**Comment by Nautiyalsachin** [comment] 2021-05-12 07:31
@sivaLeo Please try above FAQs to validate your integration, also please try running our [Sample App](https://github.com/razorpay/react-native-razorpay/tree/master/example/SampleProject), let us know if you still face any issues.

**Comment by sivaLeo** [comment] 2021-05-12 07:32
Debug Mode already set as  **yes**

**Comment by vineeth-vk11** [comment] 2021-05-12 07:43
@Nautiyalsachin I have tried setting Build Active Architecture Only to Yes in both Debug and Release but the issue it still there.

**Comment by sivaLeo** [comment] 2021-05-12 07:47
@Nautiyalsachin
Still i'm getting that error bro

**Comment by Nautiyalsachin** [comment] 2021-05-12 12:06
@vineeth-vk11 Are you using M1 powered MacBook? 

@sivaLeo can you tell me the razorpay pod version from podfile.lock. You can find this file inside iOS folder.

**Comment by Nautiyalsachin** [comment] 2021-05-12 13:49
@vineeth-vk11 I would recommend you to use Rosetta 2. For more details see this [link](https://support.apple.com/en-in/HT211861).

**Comment by vineeth-vk11** [comment] 2021-05-12 13:57
@Nautiyalsachin I have tried by enabling Rosetta 2 already but it did not solve the issue, I have compared the build settings of the sample app and my app, they are also the same. Any other suggestions?

**Comment by vineeth-vk11** [comment] 2021-05-12 14:15
@Nautiyalsachin I am able to regenerate the error with SampleProject on my Mac now.

Here are the list of changes I have made to the code to make it run

package.json dependencies upgraded to following versions
"react": "16.13.1",
"react-native": "~0.63.4",
"react-native-razorpay": "^2.2.4"

Podfile.lock
razorpay pod version updated to 1.1.12

I have completely changed the pod file to this

//Podfile Start

require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '10.0'

target 'SampleProject' do
  
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

end

//Podfile End

With these I was able to get the error.

can you tell me if changing the pod file is causing the issues?

**Comment by sivaLeo** [comment] 2021-05-12 14:21
hey @Nautiyalsachin @vineeth-vk11,
Now its working
This is my side issue. before I manually linked the razor-pay. So the configuration lines are still in pb.xproj file even i uninstall the razor-pay in my project.
so that im unlink the razor pay then uninstall the plugin.
```
npx react-native unlink react-native-razorpay
npm uninstall --save react-native-razorpay

```
Then im searching with key razor-pay in vs-code global search its shows two lines of code  in project.pbxproj. so i delete the line of codes and run pod install it remove previous razorpay-pod.
previous time i'm not seeing that line **"removing razorpay-pod"** - its explaining what i missed.

------ Thank you for your time to debug with me ------

**Comment by Nautiyalsachin** [comment] 2021-05-13 03:36
@sivaLeo Glad that you are able to solve it on your own, I would also recommend you to use auto-linking, so that you don't face these issue in future.

@vineeth-vk11 Can you share the errors here?

**Comment by vineeth-vk11** [comment] 2021-05-13 04:05
@Nautiyalsachin I am attaching a screenshot of the errors I got in the SampleProject, they are the same in my project too

<img width="258" alt="Screenshot 2021-05-13 at 9 29 25 AM" src="https://user-images.githubusercontent.com/46136355/118075590-f67d3380-b3cd-11eb-9cdd-f584422a2546.png">

I made changes to the Podfile and Package.json in the SampleProject to get the issue.

<img width="1093" alt="Screenshot 2021-05-13 at 9 32 00 AM" src="https://user-images.githubusercontent.com/46136355/118075811-73101200-b3ce-11eb-9701-1d9e5a7a6d91.png">

<img width="1135" alt="Screenshot 2021-05-13 at 9 32 31 AM" src="https://user-images.githubusercontent.com/46136355/118075823-76a39900-b3ce-11eb-8091-8e523f6757a8.png">

**Comment by Nautiyalsachin** [comment] 2021-05-13 04:12
@vineeth-vk11 Can you try creating a sample app from scratch and then try to integrate react-native-razorpay plugin, let me know if you face any issues there. I would recommend following the auto-linking process. Let me know how it goes for you. Thanks.

**Comment by vineeth-vk11** [comment] 2021-05-13 05:11
@Nautiyalsachin I have created a new project using expo. Following are the steps I followed

1. expo init RazorpayTest
2. expo eject
3.npm install --save react-native-razorpay
4. cd ios
5. pod install
6. pod update

After this I opened the project in xcode 
Build in debug configuration is successful
After changing the build configuration to release I got the same errors

**Comment by Nautiyalsachin** [comment] 2021-05-13 08:15
@vineeth-vk11 Oh got the issue, you can't integrate our app with the expo. As we are using some native functionality here and that is not supported by the expo framework. For more details - see the expo's [limitation](https://docs.expo.io/introduction/why-not-expo/). Let me know if you need any more details. Closing this issue, feel free to add more comments or reopen a new issue.

**Closed by Nautiyalsachin** 2021-05-13 08:15 UTC

**Comment by vineeth-vk11** [comment] 2021-05-13 09:06
@Nautiyalsachin I am not using react-native-razorpay in expo managed work flow, I am using it in bare work flow.

Also, I created a new project with react native CLI and the issue is still there.

So expo is not the issue.

**Comment by Nautiyalsachin** [comment] 2021-05-13 10:08
@vineeth-vk11 Is the error is same for both cases?

**Comment by Nautiyalsachin** [comment] 2021-05-13 10:10
@vineeth-vk11 Please share the sample app here, so that I can download and try to debug it.

**Comment by vineeth-vk11** [comment] 2021-05-13 12:40
@Nautiyalsachin yes the error is same in both the cases.

I am attaching both the apps - React native CLI and expo ejected app

My Xcode version - 12.5
node version - 16.1.0
npm version - 7.11.2


[RazorpayTest.zip](https://github.com/razorpay/react-native-razorpay/files/6472455/RazorpayTest.zip)
[RazorpayApp.zip](https://github.com/razorpay/react-native-razorpay/files/6472456/RazorpayApp.zip)

**Comment by vineeth-vk11** [comment] 2021-05-13 14:19
@Nautiyalsachin I installed Xcode 11.4 beside my Xcode 12.5.

Though xcode 11 is not supported on Big Mac Sur, I used the following solution to run it and to see if it can compile.

https://stackoverflow.com/questions/64983664/is-it-possible-to-run-xcode11-in-macos-big-sur

I was able to compile the code successfully on xcode 11.4 in both debug and release config.

So can we assume that the problem is there with xcode 12.5 ?

**Comment by vineeth-vk11** [comment] 2021-05-14 04:48
@Nautiyalsachin did you get a chance to look into the sample apps?

**Comment by Nautiyalsachin** [comment] 2021-05-14 15:20
@vineeth-vk11  can you try uninstalling and installing the plugin again. Let me know if this solves the issue. Thanks.

**Comment by vineeth-vk11** [comment] 2021-05-14 15:41
@Nautiyalsachin I have tried doing it multiple times but it does not work.

Were you able to compile the above sample apps on xcode 12 ?

**Comment by Nautiyalsachin** [comment] 2021-05-14 16:50
@vineeth-vk11 I recently updated the Razorpay-pod which will address the xcode 12.5 issue, latest pod is 1.1.13. You can confirm your pod version by checking podfile.lock in your ios folder.

**Comment by vineeth-vk11** [comment] 2021-05-14 17:30
@Nautiyalsachin yes pod version is 1.1.13 and it has the same error

I am attaching the sample project code below, I have not modified anything in the code. I only ran below steps before compiling on xcode

1. npx react-native init Razorpay
2. npm install react-native-razorpay --legacy-peer-deps
3. cd ios & pod install

Been looking for solutions and working on it for last 3days but unable to find the issue.

[Razorpay.zip](https://github.com/razorpay/react-native-razorpay/files/6480286/Razorpay.zip)

**Comment by Nautiyalsachin** [comment] 2021-05-15 04:42
Hi @vineeth-vk11, I tried the above sample app and it worked fine for me, here is the steps I did in the above sample app :

1. npm install
2. pod install from ios folder as pod were missing
3. Assigned developer team. 

Here is the attached sample app. 

I would also recommend you check the default XCode version in your system. You can go in XCode > Preferences > Locations > Command Line Tools > Select XCode 12.5.

[Razorpay.zip](https://github.com/razorpay/react-native-razorpay/files/6482131/Razorpay.zip)

**Comment by vineeth-vk11** [comment] 2021-05-15 06:14
Hi @Nautiyalsachin , I have downloaded the above attached sample code and the issue still there.

I have selected command line tools to xcode 12.5

I am using

Node - v 16.1.0
NPM - v 7.11.2
cocoapods - v 1.10.1

Can you tell me your node, npm and cocoapods versions ?

**Comment by punndcoder28** [comment] 2021-05-15 07:58
@vineeth-vk11 @Nautiyalsachin I am also facing the same issue on our project. I have 

react-native-razorpay 2.2.5
razorpay-pod 1.1.13
Node - v 16.0.0
NPM - v 7.10.0
cocoapods - v 1.10.1

**Comment by vineeth-vk11** [comment] 2021-05-15 09:27
@punndcoder28 I am starting to think that M1 macs might have this issue because I am also running on M1 mac.

Though I selected run on rosetta in my xcode info the issue is still there.

**Comment by vineeth-vk11** [comment] 2021-05-15 10:01
@Nautiyalsachin @punndcoder28 yes it is confirmed that issue is with arm64 on M1 mac

case 1 -
Opened the terminal normally
npx react-native run-ios
Build Failed

case 2 - 
I enabled "Open with Rosetta" for terminal and opened the terminal again
npx react-native run-ios
Build successful

But the same does not work for Xcode. Even if I am opening the xcode after enabling "Open with Rosetta" it is compiling the code using arm64 and not x86.

Not sure how it can be changed to compile in x86 on xcode.

**Comment by punndcoder28** [comment] 2021-05-15 12:51
@vineeth-vk11 Your Xcode point makes sense, but for me even when I ran terminal with rosetta build failed.

**Comment by vineeth-vk11** [comment] 2021-05-15 13:23
@punndcoder28 can you paste the error you got when you ran with rosetta on the terminal ?

**Comment by punndcoder28** [comment] 2021-05-16 05:32
> @vineeth-vk11 Your Xcode point makes sense, but for me even when I ran terminal with rosetta build failed.

@vineeth-vk11 @Nautiyalsachin I should be corrected. Works with rosetta 2 on terminal, but fails with Xcode like @vineeth-vk11 mentioned.

**Comment by vineeth-vk11** [comment] 2021-05-16 05:53
@punndcoder28 thanks for confirming

@Nautiyalsachin any workaround to compile using x86 instead of arm64 on Xcode until the issue is resolved ?

**Comment by vineeth-vk11** [comment] 2021-05-17 06:32
@Nautiyalsachin  any updates on the issue ?

**Comment by Nautiyalsachin** [comment] 2021-05-17 06:53
@vineeth-vk11 Can you share the error you are getting here?

**Comment by vineeth-vk11** [comment] 2021-05-17 07:26
@Nautiyalsachin this problem is there on M1 macs

Opening the terminal with Rosetta and running react-native run-ios works but without rosetta it gives the errors.

Even though xcode is opened with Rosetta it still uses arm64 to compile the code and not x86

Image of the error is attached

<img width="258" alt="118308855-16197680-b50a-11eb-9704-776973aa904c" src="https://user-images.githubusercontent.com/46136355/118448044-1c2c7480-b70f-11eb-8b6a-ef757966e409.png">

**Comment by Nautiyalsachin** [comment] 2021-05-17 08:33
Try changing **Validate Workspace** to **YES** in the Build Settings tab and let me know if the error still persists.

**Comment by vineeth-vk11** [comment] 2021-05-17 08:55
@Nautiyalsachin yes the error still persists after changing the Validate Workspace to YES in build settings.

**Comment by Nautiyalsachin** [comment] 2021-05-17 11:00
@vineeth-vk11  Can we get on a call, I want to see your implementation and build settings.

**Comment by niyatiArunk** [comment] 2021-05-17 11:06
Same issue, exists for me, I have a production app in Android that works fine, but while archive it was not working, need this to get resolved

**Comment by Nautiyalsachin** [comment] 2021-05-17 11:12
Hi @niyatiArunk, Have you gone through our [FAQs](https://github.com/razorpay/react-native-razorpay/wiki/FAQ's) and added asked changes? Let me know if you still face any issues, I also recommend you to go through this thread and do the asked changes.

**Comment by vineeth-vk11** [comment] 2021-05-17 14:10
@Nautiyalsachin yes we can do it, l have contacted you on LinkedIn.

@niyatiArunk can you confirm if you are using a M1 Mac or a normal Mac ?

**Comment by niyatiArunk** [comment] 2021-05-18 04:50
I am using Mac mini, it works fine now archive succeded.

**Comment by vineeth-vk11** [comment] 2021-05-18 07:08
@Nautiyalsachin thanks for the solution

https://khushwanttanwar.medium.com/xcode-12-compilation-errors-while-running-with-ios-14-simulators-5731c91326e9

I followed the steps in this but in xcode 12.5 there is no step 2. Only step 1 will do.

Following are the steps I have used to fix the issue

Step 1 - Added the below code to the Pod file

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end

Step 2 - Run the following commands in the ios folder

rm -rf ~/Library/Developer/Xcode/DerivedData/
pod deintegrate
pod update

Step 3 - In Xcode

Clean the build folder and compile

I am attaching a photo of the modified Podfile

<img width="763" alt="Screenshot at May 18 12-37-09" src="https://user-images.githubusercontent.com/46136355/118607079-cd95dd80-b7d5-11eb-8e90-8e33c7720f09.png">

@punndcoder28 please try the above steps and confirm it is working for you.

**Comment by punndcoder28** [comment] 2021-05-18 13:21
Build works from Xcode thanks @Nautiyalsachin @vineeth-vk11 !!

**Comment by harshiththota** [comment] 2021-06-24 04:10
Hello, I am facing the same issue, after trying all the above-mentioned steps, still it did not work.
node: 13.11.0
react-native: 0.61.4
macOS: 11.4
Xcode: 12.5.1
react-native-razorpay: 2.2.1

**Comment by vineeth-vk11** [comment] 2021-06-24 04:35
@harshiththota can you share a screenshot of your pod file code? Thanks

**Comment by harshiththota** [comment] 2021-06-24 05:08
<img width="1440" alt="MicrosoftTeams-image (1)" src="https://user-images.githubusercontent.com/15308181/123205843-3a3c8000-d4d8-11eb-831f-9ef34759d41c.png">
Hi @vineeth-vk11, here is screenshot of pod file, thank you.

**Comment by vineeth-vk11** [comment] 2021-06-24 05:14
@harshiththota I would like to see where you have implemented the suggested step 1 which I am entering below.

post_install do |installer|
installer.pods_project.build_configurations.each do |config|
config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
end
end

Thank you

**Comment by harshiththota** [comment] 2021-06-24 05:28
<img width="1440" alt="MicrosoftTeams-image (1)" src="https://user-images.githubusercontent.com/15308181/123207473-0dd63300-d4db-11eb-9091-134cd15b18e2.png">
 @vineeth-vk11, We have added. the mentioned code in pod file, still it did not worked

**Comment by vineeth-vk11** [comment] 2021-06-24 05:36
@harshiththota I suggest you do all the steps given in this comment - https://github.com/razorpay/react-native-razorpay/issues/331#issuecomment-842913500

If it still does not work, create a new project and implement the payment gateway and see if you are still facing the issue.

I would also like you try opening your terminal using rosetta and compile your code from the terminal to see what happens. 

Try all these and let me know what happens.

Thank you

**Comment by harshiththota** [comment] 2021-06-24 05:40
We had gone through the link and followed all the steps, it didn't work. We have created the new project and tried integration of react-native Razorpay, it builds successfully. And our mac processor is Intel.

**Comment by vineeth-vk11** [comment] 2021-06-24 05:56
@harshiththota I suggest you undo the step where you have added the code in pod file because it is to resolve the problem in M1 macs. 

@Nautiyalsachin can help you solve this issue.

**Comment by harshiththota** [comment] 2021-06-24 09:36
@vineeth-vk11, I uninstalled and reinstalled the react-native Razorpay. It is working fine now. Thank you.

**Comment by shivamvk** [comment] 2021-06-29 10:07
Has anyone found a solution to this? I'm also facing similar issues with the following config:

- Xcode 12.5
- react-native-razorpay 2.2.7
- react-native 0.63.4
- Macbook pro macOS 11.4 intel chip

The errors are similar to the screenshot attached above and I've tried everything mentioned above.

@Nautiyalsachin Are you guys not able to resolve this? My app has to go to production today and I'm stuck on this issue for past 2 days.

**Comment by harshiththota** [comment] 2021-06-29 10:50
@shivamvk uninstall, clean, and reinstall the Razorpay SDK. After doing this, in my case, it worked fine.

**Comment by shivamvk** [comment] 2021-06-29 10:55
@harshiththota Tried this several times. Didn't work.

**Comment by shivamvk** [comment] 2021-06-29 16:26
I was able to create a build by selecting 'any iOS device' in the devices list. This solved my issue for creating a build and uploading it to App Store. But if I've to run my app in release mode then this issue is still there.

**Comment by devalok1508** [comment] 2021-10-05 00:56
For M1 chip users follow this FAQ and after that clean and update pod 
[https://github.com/razorpay/react-native-razorpay/wiki/FAQ's]

**Comment by devalok1508** [comment] 2021-10-05 01:00
For M1 users follow the link FAQ and update your pod and clean project then work .[https://github.com/razorpay/react-native-razorpay/wiki/FAQ's]()

**Comment by nikhil8725** [comment] 2021-12-07 20:38
Hi @vineeth-vk11 & @Nautiyalsachin , 
I have every step you guys mentioned , still my build is getting failed . 
Here is my configuration : 
MacOS Big Sur v11.4 Apple M1 2020
Xcode Version : 13.1
react-native-razorpay : 2.2.6

<img width="627" alt="Screenshot 2021-12-08 at 2 03 37 AM" src="https://user-images.githubusercontent.com/24876605/145102640-71bc3ff0-f8f5-4ddb-bf9b-12b27ea36e5e.png">
<img width="257" alt="Screenshot 2021-12-08 at 2 03 25 AM" src="https://user-images.githubusercontent.com/24876605/145102727-e08ada51-463a-478d-a064-e0caf630ea97.png">

**Comment by devalok1508** [comment] 2021-12-08 02:58
Razorpay/React-Native-Razorpay ios not support

**Comment by SHIVAJIKUMAR007** [comment] 2022-01-19 05:29
this is all because of this new Apple M1 chip

do this step and it will work fine 

![image](https://user-images.githubusercontent.com/55244409/150069774-77dbdd98-42e3-4d82-99e8-516285a817b0.png)
