### ISSUE TITLE
'native module cannot be null'

### ISSUE THREAD

**Issue by captn3m0** [razorpay/react-native-razorpay#22] opened 2017-04-26 09:01 UTC
Issue reported over chat for iOS

**Comment by akshaybhalotia** [comment] 2017-04-26 09:27
Need more information to help with this. Send stacktrace and try some fixes as suggested by Google.

[LMGTFY](http://bfy.tw/BRHN)

**Comment by akshaybhalotia** [comment] 2017-08-29 09:27
No activity on this for long, closing for now.

**Comment by jaspal747** [comment] 2017-09-08 15:18
Receiving this error on iOS

![screen shot 2017-09-08 at 11 14 12 am](https://user-images.githubusercontent.com/1780300/30218407-fcc0f606-9486-11e7-9d13-76be8edece0c.png)

**Comment by jaspal747** [comment] 2017-09-08 15:36
Was able to resolve this by relaunching the simulator and the terminal (react-native run-ios).

Thanks

**Comment by ccupal** [comment] 2018-04-13 06:02
![simulator screen shot - iphone x - 2018-04-13 at 11 30 03](https://user-images.githubusercontent.com/32872520/38719156-1aab06a2-3f0e-11e8-84bf-a62c5a070ee3.png)
I am getting same problem, i did [Was able to resolve this by relaunching the simulator and the terminal (react-native run-ios).], but error still persists.

Thanks in advance.

**Comment by iThink32** [comment] 2018-04-13 06:33
Hey please provide more details as in which version of our package are you using and which version of  Xcode are you using?. If you are not using version 2.0.3 or react-native-razorpay , update to the latest version i.e 2.0.3 and try.

**Comment by ccupal** [comment] 2018-04-13 09:06
I am using Expo V^23.0.4, RN V0.50.3, React V16.0.0, RazorPay V^2.0.3.

**Comment by iThink32** [comment] 2018-04-13 09:18
did your issue get solved?

**Comment by ccupal** [comment] 2018-04-13 09:41
My problem is not solved yet in IOS, but in android i am able to see:  error alert through this line:
alert(`Error: ${error.code} | ${error.description}`);

**Comment by iThink32** [comment] 2018-04-13 10:13
I can help you integrate it in react-native , can u tell me your integration steps so that I can verify it

**Comment by ccupal** [comment] 2018-04-13 11:33
# I followed these steps:
1. $ npm i react-native-razorpay --save
2. $ react-native link react-native-razorpay
Linking Result:
rnpm-install info Linking react-native-razorpay android dependency 
rnpm-install info Android module react-native-razorpay has been successfully linked 
rnpm-install info Linking react-native-razorpay ios dependency 
rnpm-install info iOS module react-native-razorpay has been successfully linked

3. I have created screen with these codes: https://github.com/razorpay/react-native-razorpay/blob/master/example/index.js

## Once i Run the project from terminal: $ npm start
### IOS:
Error in red Screen coming as "native module cannot be null" in IOS (Note: error not coming if i am removing this line "import RazorpayCheckout from 'react-native-razorpay';", but we must need to import "RazorpayCheckout")

### Android:
After clicking on PAY:
![whatsapp image 2018-04-13 at 4 31 39 pm](https://user-images.githubusercontent.com/32872520/38731557-76f65f0e-3f38-11e8-8a3f-e1394c56aef8.jpeg)

4. I downloaded IOS SDK -Razorpay(with bit code enabled) from https://rzp-mobile.s3.amazonaws.com/ios/checkout/1.0.12/RazorpayBitcodeX9.framework.zip

5. I Unzipped above downloaded file, and i open "myProject.xcodeproj" with Xcode (as i have a file at location: $Project/IOS/myProject.xcodeproj)

6. then i followed these steps:

> -Download the SDK from above and unzip it.
> -Open your project in XCode and go to file under Menu. Select Add files to "yourproject".
> -Select Razorpay.framework in the directory you just unzipped.
> -Select the Copy items if needed check-box.
> -Click Add.
> -Navigate to Target settings > General and add the Razorpay.framework in both Embeded Binaries and Linked Frameworks and Libraries.
> 

 (Note: After adding [Razorpay.framework] into "Embeded Binaries" it is also showing in the "Linked Frameworks and Libraries", so i skipped to add)

i am not able to follow the steps from: https://razorpay.com/docs/ios/#step-2-initialize-the-razorpay-sdk

**Comment by iThink32** [comment] 2018-04-13 12:35
Hey I believe there is something wrong in the way you are integrating the sdk ,you cannot add the framework directly to the project you have to add it under libraries and then add the static library to your main projects Link binary with libraries (this step should only be used if react-native link react-native-razorpay fails) .Moreover the steps which you have sent is not in accordance with the readme , please follow this link and reply on   integrations@razorpay.com if you still face any further issue.

https://github.com/razorpay/react-native-razorpay

**Comment by ccupal** [comment] 2018-04-13 13:28
# it doesn't work with the tools like expo which doesn't support native modules.
It's my mistake, i had not seen **"Things to be taken care:"**
here Link: https://github.com/razorpay/react-native-razorpay

Because i had already mentioned in reply as **_I am using Expo V^23.0.4, RN V0.50.3, React V16.0.0, RazorPay V^2.0.3._**

<img width="848" alt="screen shot 2018-04-13 at 6 49 49 pm" src="https://user-images.githubusercontent.com/32872520/38737232-31bf5832-3f4c-11e8-83fa-fc4be852e64e.png">

**Comment by iThink32** [comment] 2018-04-13 14:14
closing the ticket as the issue is resolved.

**Comment by Prateek479** [comment] 2018-06-26 07:47
@iThink32  : can you please help me with the integration , I followed all the steps mention in manual process , getting this error finally . 


```
Check dependencies


Not running swift-stdlib-tool: ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES is enabled, but the product type 'Static Library' is not a wrapper type.

Unable to run command 'Libtool libRazorpayCheckout.a' - this target might include its own product.



** BUILD FAILED **



The following build commands failed:
	Check dependencies
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/addUpMath.app
An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):
This app could not be installed at this time.
Underlying error (domain=MIInstallerErrorDomain, code=4):
	Failed to chmod /Users/pojha/Library/Developer/CoreSimulator/Devices/7F446955-5229-42CE-A97F-94F6E0FB22E8/data/Library/Caches/com.apple.containermanagerd/Bundle/Application/234FE417-42B6-40A2-9DE9-C004C5523294/addUpMath.app/addUpMath : No such file or directory

```

**Comment by iThink32** [comment] 2018-06-26 08:01
Hey @Prateek479  We now have integration videos , you can watch this and try it , if you still face issues ill help you fix it.

The link is https://youtu.be/hE-F0QqTwnI.

All these links will be uploaded on our docs page but for now you can use this.

**Comment by iThink32** [comment] 2018-06-27 06:32
closing as this issue is fixed

**Closed by iThink32** 2018-06-27 06:32 UTC

**Comment by codebymani** [comment] 2019-07-30 13:08
Everything working fine till Xcode 10.1 and react-native-razorpay: 2.1.23

I have updated my Xcode from 10.1 to 10.3. when I trigger "RazorpayCheckout.open()" it pops  'native module cannot be null' error. Surprisingly If linking fails, It should pop the error on launch. But It's popping when I call RazorpayCheckout.open().

I'm unable to figure out exactly what happening under the hood.

**Comment by Prateek479** [comment] 2019-08-06 09:12
great Job @iThink32 , looks good to me 👍

**Comment by rahul0090392** [comment] 2019-11-07 06:23
Did all the steps give in above video @iThink32 . But build fails with error Library not found for - IDoubleConversion
