### ISSUE TITLE
iOS Archiving "bitcode bundle" could not be generated - Flutter

### ISSUE THREAD

**Issue by ShrutiThakur01** [razorpay/react-native-razorpay#296] opened 2020-09-30 09:45 UTC
Hi ,

I am facing this issue and unable to release the app in Appstore. App is already in App Store and i want to release a new version now. This issue is in my latest build . I am able to build the product and its also running properly on iOS devices.
When i select product==> archive then its showing as build failed.

error ==>

ld: bitcode bundle could not be generated because '/Users/XXX/XXX/XXX/ios/Flutter/Flutter.framework/Flutter' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Users/XXX/XXX/XXX/ios/Flutter/Flutter.framework/Flutter' for architecture armv7

clang: error: linker command failed with exit code 1 (use -v to see invocation)

pubspec.yaml ==>  razorpay_flutter: ^1.1.3
xcode version ==>  Version 11.2.1

In my podfile.lock ==>

razorpay-pod (1.1.5)
  - razorpay_flutter (1.1.5):
    - Flutter
    - razorpay-pod

In my pod file ==>

platform :ios, '10.0'
config.build_settings['ENABLE_BITCODE'] = 'YES'
config.build_settings['SWIFT_VERSION'] = '5.2'

Please help.

Thanks,
Shruti

**Comment by Prajwal625** [comment] 2020-10-05 11:08
Hi Shruti, 
The cause for the above issue and its solution is mentioned in the below link, please have this checked:
https://www.programmersought.com/article/34424154032/

**Comment by Nautiyalsachin** [comment] 2020-10-09 07:30
Hi @ShrutiThakur01, Please try to enable the bitcode in your code as suggested in the above link, let me know if this issue still persists, closing this issue now, feel free to reopen.

**Closed by Nautiyalsachin** 2020-10-09 07:30 UTC
