### ISSUE TITLE
redefinition of 'Razorpay' as different kind of symbol

### ISSUE THREAD

**Issue by GeekRishabh** [razorpay/react-native-razorpay#275] opened 2020-07-14 08:06 UTC
"react": "16.9.0",
    "react-native": "0.61.5",
   "react-native-razorpay": "2.1.35",

**Comment by vishnu-evolvier** [comment] 2020-07-15 13:18
I am also facing this issue.

"react": "16.13.1",
"react-native": "0.63.1",
"react-native-razorpay": "^2.1.35"

temporary fix
![oie_cSprQsl4N0ih](https://user-images.githubusercontent.com/32571612/87549579-a0ffc980-c6cb-11ea-877a-459279b29d04.png)

**Comment by ankitjaiswal1994** [comment] 2020-07-16 07:36
@vishnu-evolvier Thanks temporary solutions worked. But I hope it does not break any feature.

**Comment by iamgulfam** [comment] 2020-07-16 12:51
Same issue here,

`"react": "16.9.0",
 "react-native": "^0.61.5",
 "react-native-razorpay": "^2.1.31"`

need permanent fix.

**Comment by rams12** [comment] 2020-07-16 16:00
Is android working?

**Comment by aayushanand99** [comment] 2020-07-17 10:31
For android I had to change implementation 'com.razorpay:checkout:1.5.18' to implementation 'com.razorpay:checkout:1.5.12'
in app/build.gradle

**Comment by sumedht** [comment] 2020-07-21 07:15
@aayushanand99 @rams12 @iamgulfam 
We have figured out the issue and it will be fixed in the next release. In the meantime, we would suggest that you don't use the previous versions and use the newer one instead as it has new features.
Add these two lines to app-level build.gradle


> implementation 'com.google.android.gms:play-services-auth:17.0.0'
> implementation 'com.google.android.gms:play-services-auth-api-phone:17.1.0'

and it should start working without a hitch. We'll also be adding this to the documentation. Please post here if you face any further issues.

**Comment by sathishu37** [comment] 2020-07-22 09:55
> redefinition of 'Razorpay' as different kind of symbol

@sumedht Same issue persists in the latest version also.

```
"react": "^16.8.6", 
"react-native": "^0.60.0",
"react-native-razorpay": "^2.1.36"
```

**Comment by Biplovkumar** [comment] 2020-07-23 05:03
same here.
working in Android but not in IOS.
I am stuck from 5 days.
pls help.

**Comment by Nautiyalsachin** [comment] 2020-07-23 05:07
Which pod version are you guys using?

**Comment by Biplovkumar** [comment] 2020-07-23 05:08
> I am also facing this issue.
> 
> "react": "16.13.1",
> "react-native": "0.63.1",
> "react-native-razorpay": "^2.1.35"
> 
> temporary fix
> ![oie_cSprQsl4N0ih](https://user-images.githubusercontent.com/32571612/87549579-a0ffc980-c6cb-11ea-877a-459279b29d04.png)

thanks @vishnu-evolvier  you saved my day.

its a big bug of react-native-razorpay because with it not able to run project.

**Comment by Biplovkumar** [comment] 2020-07-23 05:09
> Which pod version are you guys using?

platform :ios, **'10.0'**

**Comment by Nautiyalsachin** [comment] 2020-07-23 05:30
Please update the razorpay-pod -> 1.1.5 so that you don't have to do the above fix. 

Or use **pod update** for fixing this issue, this will automatically update your Razorpay pod to the latest version.

Here are the detailed steps via this [link](https://freakycoder.com/ios-notes-12-how-to-update-pods-249ecf88fe57) which you can follow.

**Comment by aayushanand99** [comment] 2020-07-24 19:55
@sumedht build is failing.
![image](https://user-images.githubusercontent.com/10920961/88430225-b2587c80-ce15-11ea-89c9-7df4c7992ae8.png)

**Comment by abhilekhsingh041992** [comment] 2020-07-25 12:32
I am facing the same issue in version 2.1.36.

For now, I'm using the **older version: 2.1.25**, which doesn't have this issue. But please do fix it.

**Comment by vivekshindhe** [comment] 2020-07-25 13:51
@aayushanand99 the image doesn't help in debugging the cause for this. Could you please send the logs for the same? We'll be able to get back to you on this pretty quick with them.

**Comment by vivekshindhe** [comment] 2020-10-21 10:49
Closing this issue due to no response from your side. Please feel free to either re-open the issue or create a new issue if you have any additional queries.

**Closed by vivekshindhe** 2020-10-21 10:49 UTC
